--
-- Database loading script: `internWiz`
--
LOAD DATA LOCAL INFILE "employers.csv" INTO TABLE Employers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "students.csv" INTO TABLE Students FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "jobs.csv" INTO TABLE Jobs FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "faculty.csv" INTO TABLE Faculty FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "referrals.csv" INTO TABLE Referrals FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';


